name: Makefile CI

on:
  push:
    branches: [ "slaveholder" ]
  pull_request:
    branches: [ "slaveholder" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: nasm
        uses: ilammy/setup-nasm@v1.5.2
      - name: compile check
        run: make all
